name: Daily Diff

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day (change cron for different timings)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-diff:
    strategy:
      matrix:
        repo: ["rohittp0/AutoREPL"]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: host

      - name: Checkout ${{ matrix.repo }}
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          path: guest
          # token: ${{ secrets.PA_TOKEN }}  # Uncomment and configure in GitHub secrets to use private repositories

      - name: Setup Repository Environment
        run: |
          cd host
          git checkout -b ${{ matrix.repo }} || git checkout ${{ matrix.repo }}
          mkdir diffs

      - name: Get Repository Description
        run: curl -sSL -X GET "https://api.github.com/repos/${{ matrix.repo }}" | jq -r '.description' > host/description.txt

      - name: Find First Commit in Last 24 Hours
        id: find-commit
        run: |
          cd guest
          FIRST_COMMIT=$(git rev-list --since="1 day ago" HEAD | tail -n 1)
          if [ -z "$FIRST_COMMIT" ]; then
            echo "No commits in the last 24 hours."
            exit 0  # Exit the workflow successfully without error
          fi
          echo "FIRST_COMMIT=$FIRST_COMMIT" >> $GITHUB_ENV

      - name: Get Git Diff
        run: |
          cd guest
          DIFF_INDEX=$(ls ../host/diffs | wc -l)
          git diff $FIRST_COMMIT HEAD > ../host/diffs/${DIFF_INDEX}.txt

      - name: Commit and Push Changes
        run: |
          cd host
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update diffs for ${{ matrix.repo }} at $(date)"
          git push -u origin ${{ matrix.repo }}
