name: Python Script Runner

on:
  push:
    paths:
      - 'diffs/**'
  pull_request:
    paths:
      - 'diffs/**'

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          save-always: true
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py
      
      - name: Get Output File
        shell: bash
        run: |
            POST="$(cat 'posts/next.md')"
            REPO=$(cat repo.json | jq -r '.full_name')
            echo "POST=$POST" >> $GITHUB_ENV
            echo "REPO=$REPO" >> $GITHUB_ENV
      
      - name: Notify Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data \
          '
          "text": "WatchPost Daily Update for $REPO",
          "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "$POST"
              }
            },
            {
              "type": "actions",
              "elements": [
                {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "View on :github:"
                  },
                  "url": "${{ github.server_url }}/${{ github.repository }}/blob/${REPO}/posts/next.md"
                }
              ]
            }
          ]
          '
          "$SLACK_WEBHOOK_URL"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATIONS_TOKEN }}
