name: Daily Diff

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day (change cron for different timings)
  workflow_dispatch:

jobs:
  check-diff:
    strategy:
      matrix:
        repo: ["rohittp0/AutoREPL"]
        
    runs-on: ubuntu-latest
    steps:
      - name: send-diff
        uses: ./.github/send-diff
        with:
          repo: ${{ matrix.repo }}
      
